services: 
  - type: web 
    name: smartticket-ai 
    runtime: python 
    buildCommand: pip install -r requirements.txt 
    startCommand: streamlit run "new nlp/ticket_nlp/app.py" --server.port $PORT --server.address 0.0.0.0 
    envVars: 
      - key: PYTHON_VERSION 
        value: 3.10.0 
